#!/usr/bin/env python3
"""Download the pinned browser libraries into ctokens/web/static/vendor/ (ADR 0002). Run by hand on upgrades:

    python3 tools/vendor.py [--skip-licenses]

Bump a version in LIBRARIES, run the script, check the diff and commit the result.
"""
import argparse
import hashlib
import sys
import urllib.request
from pathlib import Path

CDNJS = "https://cdnjs.cloudflare.com/ajax/libs"
VENDOR = Path(__file__).resolve().parent.parent / "ctokens" / "web" / "static" / "vendor"

# name: (version, license, {vendored file: path in the cdnjs release}, license URL at the release tag)
LIBRARIES = {
    "Chart.js": ("4.5.1", "MIT", {"chart.umd.min.js": "chart.umd.min.js"},
                 "https://raw.githubusercontent.com/chartjs/Chart.js/v{v}/LICENSE.md"),
    "marked": ("18.0.14", "MIT", {"marked.min.js": "lib/marked.umd.min.js"},
               "https://raw.githubusercontent.com/markedjs/marked/v{v}/LICENSE.md"),
    "dompurify": ("3.4.16", "MPL-2.0 OR Apache-2.0", {"purify.min.js": "purify.min.js"},
                  "https://raw.githubusercontent.com/cure53/DOMPurify/{v}/LICENSE"),
    "highlight.js": ("11.11.2", "BSD-3-Clause", {"highlight.min.js": "highlight.min.js",
                                                 "hljs-light.css": "styles/atom-one-light.min.css",
                                                 "hljs-dark.css": "styles/atom-one-dark.min.css"},
                     "https://raw.githubusercontent.com/highlightjs/highlight.js/{v}/LICENSE"),
}


def fetch(url):
    request = urllib.request.Request(url, headers={"User-Agent": "claude-tokens-vendor"})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read()


def sha256(data):
    return hashlib.sha256(data).hexdigest()


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--skip-licenses", action="store_true", help="do not download the license texts")
    args = parser.parse_args(argv)

    (VENDOR / "LICENSES").mkdir(parents=True, exist_ok=True)
    lines = ["# Vendored browser libraries. Generated by tools/vendor.py; do not edit by hand.",
             "# file  library  version  license  sha256  source"]
    for name, (version, spdx, files, license_url) in LIBRARIES.items():
        for target, source in files.items():
            url = f"{CDNJS}/{name}/{version}/{source}"
            data = fetch(url)
            (VENDOR / target).write_bytes(data)
            lines.append(f"{target}  {name}  {version}  {spdx}  {sha256(data)}  {url}")
            print(f"{target:20} {name} {version} ({len(data):,} bytes)")
        if args.skip_licenses:
            continue
        url = license_url.format(v=version)
        data = fetch(url)
        target = f"LICENSES/{name}.txt"
        (VENDOR / target).write_bytes(data)
        lines.append(f"{target}  {name}  {version}  {spdx}  {sha256(data)}  {url}")
        print(f"{target:20} {name} {version}")
    (VENDOR / "VERSIONS.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
